### ISSUE TITLE
[BUG] Cannot activate switches behind doors in Scythe map 18

### ISSUE THREAD

**Issue by dan5sch** [odamex/odamex#667] opened 2022-05-14 03:11 UTC
**Describe the bug**
In map 18 of Scythe, two switches that are revealed behind blue and yellow key doors cannot be activated. All other use-able linedefs in the level that I could find can be activated.

**Build that the bug occurred in**
Odamex v10.1.0 (stable, G47EEA-8311). Commit 47eeac814bc41b720279a50dec7bf7c798cdcc1c (head currently).
Built on Ubuntu 20.04 using CMake (GCC, release profile).

**To Reproduce**

1. Run `$ odamex -iwad DOOM2.WAD -file SCYTHE.WAD`
2. Change level to MAP18
3. Enter the building, collect the yellow keycard upstairs, and collect the blue keycard outside
4. Open the blue and yellow doors on the outside of the building
5. Attempt to activate the switches behind the doors

**Expected behavior**
The switches are activated.

Actual behavior: the switches do not activate. The game does **not** play the "grunt" sound.

**Screenshots, NetDemos, & Crash Dumps**
N/A

**Additional context**
If you use the idclip cheat, it's possible to activate the switches after clipping slightly into the wall.

**Comment by rakohus** [comment] 2022-05-14 03:21
Confirmed everything you reported, including clipping closer to the switch. Looks like another linedef in front of the switch is cancelling the player's use. I think this may be the same issue as exhibited in #623.

**Comment by rakohus** [comment] 2022-08-07 03:59
Fixed by #737. Hooray!

**Closed as completed by rakohus** 2022-08-07 03:59 UTC
Labels: Type-Bug, Component-Client, Component-Server, Resolution-Fixed, Subsystem-ActorBehavior, Subsystem-MapFormat
