### ISSUE TITLE
[BUG] Sky uses the wrong texture on Eviternity Map32

### ISSUE THREAD

**Issue by ShadowMosesIsland** [odamex/odamex#966] opened 2024-06-25 08:39 UTC
**Describe the bug**
Sky does not appear correctly on Eviternity map32, uses a random texture instead. Happens in both singleplayer and netplay.

**Build that the bug occurred in**
Odamex 10.5.0

**To Reproduce**
1. Launch Odamex with these parameters `odamex -iwad doom2.wad -file Eviternity.wad`
2. Type in console `map map32` OR type `idclev32` on any map.
3. Proceed until the sky is visible.

**Expected behavior**
Use the correct texture to render the sky, as seen in the DSDA-Doom screenshot.

**Screenshots, NetDemos, & Crash Dumps**
(This texture seems to appear most often)
![odamex](https://github.com/odamex/odamex/assets/131174864/3b647449-775e-4e87-9df2-dc15cf0db17c)
![odamexmap12](https://github.com/odamex/odamex/assets/131174864/6e97d959-6908-41d0-a94d-87e07d21f034)
![odamexmapnone](https://github.com/odamex/odamex/assets/131174864/29de0c9a-474f-4ed9-ad76-06759ee1576d)

_**DSDA-Doom 0.27.5 - Expected behavior**_
![DSDA](https://github.com/odamex/odamex/assets/131174864/2cd453c3-a444-419d-9f3f-a4d9290a4ff8)

**Additional context**
Could be related to #921, the bug is apparent in the provided [footage](https://www.youtube.com/watch?v=QFpie_9l8mE), but there doesn't seem to be any issue open to address it. #907 is similar, but it's not the same, as it affects every map and doesn't use any textures.

**Comment by rakohus** [comment] 2024-06-28 03:53
After some troubleshooting and looking at this with @bcahue, we both think it may be an issue with OTEX vs Odamex. Still investigating

**Comment by bcahue** [comment] 2024-07-02 16:12
It was mentioned in the Odamex Discord by Wyrewolwerowany Rewolwerowiec that this map goes over the 16-bit (65,535 iirc) sidedef limit, and they claim to have removed a ton of linedefs from the map and the result was a hacked up map but the sky did render correctly. Something to keep track of for this bug.

**Comment by bcahue** [comment] 2024-08-18 19:22
DB2 derived editors will "compress" (dedupe) sidedefs if over the sidedef limit, until that can't be done anymore and will error with "cannot save map." Source: https://www.doomworld.com/forum/post/2533315

**Comment by bcahue** [comment] 2024-08-19 03:11
Also worth noting that most skies in this map are set up using line action 272 transfer sky (flipped)

**Comment by rakohus** [comment] 2024-09-21 00:58
After an independent investigation, this appears to affect any sidedef that is > 65,535, where that sidedef has the sky transfer line special on it. Confirmed on both Eviternity 1 MAP32, as well as Eviternity 2 MAP14.

**Comment by rakohus** [comment] 2024-12-09 00:40
Fixed with PR #1087. Merged into stable today. Excellent as always @electricbrass!!!!

**Closed as completed by rakohus** 2024-12-09 00:40 UTC
Labels: Type-Bug, Component-Client, Subsystem-Renderer, Resolution-Fixed, Subsystem-Resources
