### ISSUE TITLE
[BUG] Support wider `STBAR` status bar lumps as DSDA / GZ do (1x1.wad)

### ISSUE THREAD

**Issue by Sbzro12345** [odamex/odamex#924] opened 2023-11-19 00:20 UTC
**Describe the bug**
Status bar when loading 1x1.wad looks visually glitched out.

**Build that the bug occurred in**
v10.4.0 Release version. Commit ID 46e0e1d7e6fcb8f0326884ba3331af92a3399bbc of stable branch.

**To Reproduce**
Load 1x1.wad with Odamex

**Expected behavior**
In DSDA-Doom, this is what the status bar looks like.
![image](https://github.com/odamex/odamex/assets/72307706/c61dec3c-7105-4e60-961f-328259f832de)
![image](https://github.com/odamex/odamex/assets/72307706/e678406b-5cc0-4ca4-b8b4-1d36b8c3ef8e)

**Screenshots, NetDemos, & Crash Dumps**
What shows in Odamex v10.4.0
![Odamex_COOP_20231119_032310](https://github.com/odamex/odamex/assets/72307706/6e85f019-a0ea-48e7-bd24-81def2b0691c)

**Comment by rakohus** [comment] 2024-02-12 00:58
This is caused by a `STBAR` lump that does not conform to the expected dimensions for a Doom wad. This must be a situation where DSDA supports an ultrawide status bar where Odamex, as of now, does not. The `STBAR` in 1x1.wad is 428x32, while the standard Doom `STBAR` is 320x32. 

Therefore, this is not a bug, but is actually a feature request to support wide status bars. I will amend the title of this ticket and make the name more appropriate. Thank you for reporting.

**Comment by rakohus** [comment] 2024-07-01 03:18
Related to bug #327.

**Comment by bcahue** [comment] 2024-08-27 03:23
Considered fixed with #983

**Closed as completed by bcahue** 2024-08-27 03:23 UTC
Labels: Type-Feature, Component-Client, Subsystem-Renderer, Compat-ZD2
