### ISSUE TITLE
Can't open certain boom-compatible pwad (MAPINFO crashes)

### ISSUE THREAD

**Issue by fraansg** [odamex/odamex#279] opened 2021-04-20 20:19 UTC
Although I don't find problems, in general, to load different pwads, it happens that **wos.wad** (_Whispers of Satan_, boom-compatible pwad) cannot be loaded, the port crashes when I try it. This happens in the latest release of the port (0.9.0), running in MacOS Big Sur.

I don't know why it happens, I have loaded it correctly and I have not had problems with other boom-compatible pwads, being that the pwad in question works correctly even in Boom 2.02 (the latest build of Boom in DOS).

The parameter used is the usual: odamex -iwad doom2.wad -file wos.wad.

The terminal indicates, after crashing: 42044 segmentation fault.

for more details I transcribe the crash report:

`Signal number: 11`
`Errno: 0`
`Signal code: 1`
`Fault Address: 0xffffffffffffffec`
`0   odamex                              0x0000000100f06dab _ZL17SigActionCallbackiP9__siginfoPv + 443`
`1   libsystem_platform.dylib            0x00007fff203d1d7d _sigtramp + 29`
`2   ???                                 0x00007ffeeedd7260 0x0 + 140732905910880`
`3   odamex                              0x0000000100e7cff1 _Z11HU_Shutdownv + 33`
`4   odamex                              0x0000000100e692e0 _Z10D_Shutdownv + 96`
`5   odamex                              0x0000000100ec9149 _Z10call_termsv + 89`
`6   odamex                              0x0000000100ec96b8 main + 1240`
`7   libdyld.dylib                       0x00007fff203a8621 start + 1`

**Comment by rakohus** [comment] 2021-04-20 20:21
![image](https://user-images.githubusercontent.com/22926877/115458940-6e53a600-a1f4-11eb-922c-291560863e50.png) Reproduced. corresponding MAPINFO error attached.

**Comment by leximayfield** [comment] 2021-04-22 04:28
Okay, so in theory the "new" MAPINFO lump allows you to skip tokens you don't know about, but with my adjustments to the MAPINFO parser I don't think I did an adequate job of doing so.

There is an outstanding pull request that I intend on merging that not only introduces UMAPINFO but makes changes to the MAPINFO parser that might alleviate some of these warnings.

**Comment by rakohus** [comment] 2021-04-23 19:25
Another affected wad from bug #282 : `duelpack.wad`

**Comment by leximayfield** [comment] 2021-04-24 00:38
> Another affected wad from bug #282 : `duelpack.wad`

This one is due to its use of episodes, which we do not implement at all at the moment.  UMAPINFO PR will bring that support in UMAPINFO, but I'm unsure if that will bring support into proper MAPINFO.

**Comment by rakohus** [comment] 2022-01-02 05:20
wos and duelpack both seem corrected under the UMAPINFO changes that were merged in. Tested on Oda 10 dev build today.

**Closed as completed by rakohus** 2022-01-02 05:20 UTC
Labels: Type-Bug, Component-Client
