### ISSUE TITLE
[BUG] WAD Downloads on Portable mode are set to My Documents\Games\Odamex

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#350] opened 2021-05-12 20:36 UTC
**Describe the bug**
While in portable mode, Odamex downloads PWADs within the "My Documents" folder.

**Build that the bug occurred in**
Odamex 0.9.0.

**To Reproduce**
- Make sure Odamex has no `odamex-installed.txt` file installed in its folder, no `cl_waddownloaddir` value in your odamex config.
- Run Odamex.exe
- Connect to a server with a wad you don't own through the console.
- PWAD will be saved in `My Documents\Games\Odamex`

**Expected behavior**
It should be downloaded within the folder where odamex is located.

Also, please note that the issue doesn't exist if you start through Odalaunch since it sets the waddir commandline parameter!

**Comment by rakohus** [comment] 2022-01-02 06:47
I cannot reproduce this. Does this issue still occur for you @Ch0wW?

**Comment by rakohus** [comment] 2022-02-02 22:30
No feedback. Can't reproduce. Closing.

**Closed as completed by rakohus** 2022-02-02 22:30 UTC
Labels: Type-Bug, Component-Client
