### ISSUE TITLE
[BUG] Client crash when exiting any level in Chapter 5 of 2022: A DOOM Odyssey

### ISSUE THREAD

**Issue by Sbzro12345** [odamex/odamex#922] opened 2023-11-18 19:49 UTC
**Describe the bug**
Upon exiting any level in chapter 5 of 2022ado.wad, Odamex client crashes. In multiplayer, the client also crashes. But the server moves on to the next level, so the players can just rejoin the server. Name of level in automap is also not displaying properly.

**Build that the bug occurred in**
v10.4.0 Release version. Commit ID 46e0e1d7e6fcb8f0326884ba3331af92a3399bbc of stable branch.

**To Reproduce**
Windows 11 Pro 64-bit OS, OS build 22631.2715. Exit any level of chapter 5 of 2022ado.wad. https://www.doomworld.com/idgames/levels/doom/Ports/megawads/2022ado

**Expected behavior**
Client should not crash, and move on to the next level properly. Name of map should also be displayed on automap properly.

**Screenshots, NetDemos, & Crash Dumps**
No dumps were created upon client crash, only the following error message:
```Markdown
ERROR: W_GetNumForName: WIMAP-1 not found!
(checked in: ODAMEX.WAD, DOOM.WAD, 2022ADO.WAD)
```

E5M1 exit on Singleplayer
![image](https://github.com/odamex/odamex/assets/72307706/883b70b3-3a63-4000-a858-6d1073599d89)

E5M2 exit on Multiplayer
![image](https://github.com/odamex/odamex/assets/72307706/a35dc1b2-c582-4421-9696-e2964bb90e54)

**Comment by Sbzro12345** [comment] 2023-11-18 20:00
For some reason, the e5 level names are displayed as DOOM2 levels, even though DOOM.wad is being used as the iwad. This is not the case for the other episodes though.
![Odamex_COOP_20231119_025644](https://github.com/odamex/odamex/assets/72307706/62ec763e-bfa6-4ce3-8204-c9612b71512a)

**Comment by rakohus** [comment] 2024-02-12 01:00
Duplicate of #923. Root cause is the same for both issues. Since 923 has more information in the comments, I will close this one.

**Closed as not planned by rakohus** 2024-02-12 01:00 UTC
Labels: Type-Bug, Resolution-Duplicate
