### ISSUE TITLE
Sector in PWAD 'Icarus' takes on random properties and kills or damages

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#681] opened 2022-06-25 17:40 UTC
I discovered today after playing on [NY] Survival server for Icarus Map15 that two of the sectors inherited strange properties that I can't link back to a source. On the server, running over Sector 26 (a triangle-shape floor that lowers at the start of the map) would result in an instant death. On that same server triggering a trap to reveal a Pain Elemental, the sector that opens and the sector the pain elemental was in (unsure which one I stepped in) had the same result and instantly killed me sector references are 288 and 289.

I took this offline to see if the issue persists and was related to a server CVar.

Opened the Pwad in UDB and there is nothing wrong with its calls and positioning, Sector 29 with tag 26 from a simple activation linedef and is not joined to any other sectors and it itself is a complete and closed sector.

Started the test map function the first time with Odamex, and as the wall came down I stood on it, and absolutely nothing happened.

Closed the map and opened it again and performed the same action, this time the floor was now draining 1 health per second. After I closed and reopened the map again this occured one more time.

On the 4th test of the map, the sector was fully killing me off, dropping my health to 0 after making contact. If this happens in a singleplayer session then I can only assume this is easy to replicate? Demo attached
[Demo.zip](https://github.com/odamex/odamex/files/8985294/Demo.zip)

**Comment by thefatwilly** [comment] 2022-06-25 20:53
Quick note, I did do a bit more investigation and the bug is caused by a sector that is activated by linedef action 37 "W1 Floor Lower to Lowest Floor (changes texture)"

**Comment by rakohus** [comment] 2022-06-26 03:10
Thanks for this thorough report @thefatwilly, it's much appreciated. The bad news is that you went through with doing all of the research. The good news is that we resolved this several weeks ago and it will be in the upcoming release. Duplicate of #662, resolved by PR #663.

**Closed as completed by rakohus** 2022-06-26 03:10 UTC
Labels: Type-Bug, Resolution-Duplicate, Severity-Critical, Component-Client, Component-Server, Compat-Vanilla, Subsystem-MapFormat
