### ISSUE TITLE
[BUG] Automap scrolling does not work with follow mode off

### ISSUE THREAD

**Issue by thefatwilly** [odamex/odamex#739] opened 2022-08-06 22:59 UTC
**Describe the bug**
When toggling 'follow mode' while in the Automap, attempting to move the cursor with the arrow keys will move the point to a (center of the map?) fixed location and not really budge at all.

**Build that the bug occurred in**
10.1 & 10.2 pre-release

**To Reproduce**
Just go into any map and use the automap to toggle follow mode off then try to move the map around

**Comment by electricbrass** [comment] 2022-08-16 04:59
Doesn't seem to be the center of the map. Seems consistently up and to the right of the center (So the map ends up more in the bottom left of the screen).
I'm pretty sure the issue is somewhere in AM_changeWindowLoc.

**Comment by rakohus** [comment] 2022-09-02 14:50
Fixed by @electricbrass patch. Thanks for report @thefatwilly

**Closed as completed by rakohus** 2022-09-02 14:50 UTC
Labels: Type-Bug, Component-Client, Subsystem-Renderer, Subsystem-UI, Resolution-Fixed, Compat-Vanilla
