### ISSUE TITLE
[BUG] DOOM 4 VANILLA won't work on Odamex

### ISSUE THREAD

**Issue by mmiovv2** [odamex/odamex#575] opened 2022-02-21 13:34 UTC
**Describe the bug**
DOOM 4 VANILLA, a Total Conversion mod that's supposed to work on Chocolate and modern Sourceports is crashing when it's two files (D4V.WAD and D4V.DEH) are loaded.

**Build that the bug occurred in**
10.0

**To Reproduce**
Open the total conversion (found [here](https://www.doomworld.com/forum/topic/108725-doom-4-vanilla-v32/?page=27&tab=comments#comment-2119868)) via Odamex.

**Expected behavior**
The mod should load normally as Odamex should already have full support for stuff like these implemented.

**Screenshots, NetDemos, & Crash Dumps**
(https://imgur.com/a/hTOnkLK)

**Comment by Ru5tK1ng** [comment] 2022-02-21 14:46
The following entries in ANIMDEFS are preventing the wad from loading properly:

flat FWATER1
pic ZWATER1 tics 6
pic ZWATER2 tics 6
pic ZWATER3 tics 6
pic ZWATER4 tics 6

flat FWATER2
pic ZWATER1 tics 6
pic ZWATER2 tics 6
pic ZWATER3 tics 6
pic ZWATER4 tics 6

flat FWATER3
pic ZWATER1 tics 6
pic ZWATER2 tics 6
pic ZWATER3 tics 6
pic ZWATER4 tics 6

flat FWATER4
pic ZWATER1 tics 6
pic ZWATER2 tics 6
pic ZWATER3 tics 6
pic ZWATER4 tics 6

It seems Odamex is expecting the basic Hexen syntax of pic -integer tics -integer for animated flats. Example:

flat FWATER1
pic 1 tics 6
pic 2 tics 6
pic 3 tics 6
pic 4 tics 6

**Comment by rakohus** [comment] 2022-02-21 16:36
This is a duplicate of #547. Please consider searching before submitting new issues!

**Closed as completed by rakohus** 2022-02-21 16:36 UTC
Labels: Resolution-Duplicate

**Comment by mmiovv2** [comment] 2022-02-21 17:47
I'm sorry then.
