### ISSUE TITLE
[BUG] Server still thinks client is dead despite client respawning

### ISSUE THREAD

**Issue by Ru5tK1ng** [odamex/odamex#612] opened 2022-03-07 06:49 UTC
**Describe the bug**
In a demo submitted to me, you can see D'Sparil get killed and respawn. However, after a bit he becomes unable to move and jitters in place. When he presses use he respawns again and where he was stuck previously shows a green marine.

**Build that the bug occurred in**
Oda 10

**To Reproduce**
No idea. He lagged right before death.

**Expected behavior**
Respawn normally.

**Screenshots, NetDemos, & Crash Dumps**
Demo & Timestamp:
0:52

[2022.03.05_19.39.57_doom2.wdl2021.zip](https://github.com/odamex/odamex/files/8195445/2022.03.05_19.39.57_doom2.wdl2021.zip)

**Additional context**
He probably has a connection that's been chewed by rats.

**Comment by rakohus** [comment] 2022-03-07 06:53
This is a duplicate, of sorts, with #610. The same issue is described and documented there (in bullet point 2). I'm going to close this as a duplicate of #610 for now, but may eventually break that single issue out into separate issues. If you have the time, could you please post this demo and timestamp over there as well? If we break it into its own bug, I'll take care of moving the information. Thank you!

Duplicate of #610.

**Closed as completed by rakohus** 2022-03-07 06:53 UTC
Labels: Resolution-Duplicate
