### ISSUE TITLE
[BUG] Odamex netdemos don't initialize everything properly when recording in the middle of a game

### ISSUE THREAD

**Issue by Ch0wW** [odamex/odamex#316] opened 2021-04-25 17:16 UTC
**Describe the bug**
Odamex doesn't seem to initialize actors properly when starting a netrecord whilst in the middle of a game.

**Build that the bug occurred in**
Any build from 0.9.0 has that bug built in.

**To Reproduce**
Simply load the demo to see that no actor is visible, no scoreboard is present or can't be spectated at all, at the cost of an immediate crash.

**Expected behavior**
Players should be seen and spied on, scoreboard should be already populated.

**Screenshots, NetDemos, & Crash Dumps**
[decino-demo-bug-5sec.zip](https://github.com/odamex/odamex/files/6372521/decino-demo-bug-5sec.zip)

**Comment by Ch0wW** [comment] 2021-04-25 17:44
This demo also happen to trigger the issue (requires FREEDM.wad) :

Players are invisible, yet semi-"populated" by the scoreboard (misses nickname), and the moment one of them frags a player, it crashes.
[invisibleplayer_crash.zip](https://github.com/odamex/odamex/files/6372615/invisibleplayer_crash.zip)

**Comment by leximayfield** [comment] 2021-04-25 23:49
From a cursory examination, it looks like the demo data is making it into the demo, but then the `svc_netdemoloadsnap`  message which actually loads the map seems to blow away the player array at the same time.

**Comment by leximayfield** [comment] 2021-05-14 14:25
Demos are two things in one.  They contain a record of network traffic, but they also have "key frames" that contain a set of serialized data, like a savegame.  In the broken demos I have come across, the initial snapshot is missing some or nearly all of the ingame players, and when the first snapshot is loaded, things go wacky.

However, try as I might, I have not been able to come up with a consistent reproduction of this behavior.  Any attempt I have at starting a demo in the middle of a match with `netrecord` seems to capture all of the players just fine.  So what would be most helpful is a consistent way to create busted demos I can replicate just by running a bunch of clients and a server locally.

**Comment by leximayfield** [comment] 2021-05-15 05:09
The consistent reproduction turned out to be not to use `netrecord` in the console, but to use `-netrecord` or autoplay settings.

Potential fix on the way in `bug/demo-snap-fix`, currently being tested.

**Comment by rakohus** [comment] 2021-05-27 00:06
Resolved in 0.9.1 by way of #364

**Closed as completed by rakohus** 2021-05-27 00:06 UTC
Labels: Type-Bug, Status-HelpWanted, Component-Client
