### ISSUE TITLE
[BUG] Crash while connecting

### ISSUE THREAD

**Issue by rakohus** [odamex/odamex#396] opened 2021-06-05 03:12 UTC
**Describe the bug**
Crash while connecting. -nomusic is enabled.

**Build that the bug occurred in**
bug/health-desync, 186ce

**To Reproduce**
Connect to a server. Happens often.

**Expected behavior**
Not crash

**Screenshots, NetDemos, & Crash Dumps**
[odamex_g186c_28976_20210605T030849.zip](https://github.com/odamex/odamex/files/6601938/odamex_g186c_28976_20210605T030849.zip)

**Comment by leximayfield** [comment] 2021-06-05 03:29
Duplicate of  #341 .

**Closed as completed by leximayfield** 2021-06-05 03:29 UTC
Labels: Type-Bug
