### ISSUE TITLE
[BUG] BOOM Line to Line teleport, sky flickers through walls 

### ISSUE THREAD

**Issue by Meerschweinmann** [odamex/odamex#939] opened 2024-03-07 08:45 UTC
Helloho.

When i walk over a "line to line teleport" (Line-Action 244) from a BOOM map the sky flickers through the walls every time i walk over that line.

Here is a BOOM demo map:

https://www.doomworld.com/idgames/themes/TeamTNT/boom/boomedit 

When i walk the stairs up or down from the "room over room" demo or when i walk under the iced sea in the outer area, i can see this short flicker.

Used Odamex version: 10.4.0

**Comment by rakohus** [comment] 2024-03-07 12:56
I believe this is an issue with the render interpolation. Seems to player camera to 0,0.

**Comment by Meerschweinmann** [comment] 2024-03-07 13:35
I had the framerate uncapped, if that is helpful.

**Comment by Meerschweinmann** [comment] 2024-03-07 20:15
Update: with framerate capped at 35fps the short flicker is gone. 
But even 35fps were a not really reachable dream on my 486 back in the days, it is really juddery today :)

**Comment by rakohus** [comment] 2024-07-20 13:40
Include as duplicate of #564.

**Closed as not planned by rakohus** 2024-07-20 13:40 UTC
Labels: Type-Bug, Resolution-Duplicate, Component-Client, Subsystem-Renderer, Compat-Boom
