### ISSUE TITLE
[BUG] Sector 1208 not lowering after Pinkies at the starting area die on BoSCP.wad, map05 on Multiplayer

### ISSUE THREAD

**Issue by Sbzro12345** [odamex/odamex#927] opened 2023-11-26 21:42 UTC
**Describe the bug**
In multiplayer, on BoSCP.wad map05, sector 1208 does not lower even after the Pinkies at the start die. This is not the case in Singleplayer, where the sector lowers as expected.

**Build that the bug occurred in**
v10.4.0 Release version. Commit ID 46e0e1d7e6fcb8f0326884ba3331af92a3399bbc of stable branch.

**To Reproduce**
Play BoSCP.wad map05 in multiplayer.

**Expected behavior**
Sector 1208 should lower after the Pinkies at the start die.

**Screenshots, NetDemos, & Crash Dumps**
![image](https://github.com/odamex/odamex/assets/72307706/8029025a-6008-4039-80c4-905d505e954f)
<img width="640" alt="Odamex_COOP_20231127_044115" src="https://github.com/odamex/odamex/assets/72307706/2141f802-e023-4fea-8f7f-f2a818333bed">

**Comment by rakohus** [comment] 2024-02-12 02:10
I looked into how this is setup. Killing the pinkies doesn't matter - it's entirely time based AFTER you fire a shot. Firing a shot awakens lost souls which eventually move out of the voodoo doll's way on the conveyors. In skills 1-3, it will then be a very short time for sector 1208 to drop. 

It appears that the avatars online are NOT being pushed by the conveyor floors that activate the script. The voodoo dolls offline are pushed correctly. The floor speed is determined by a tag to action 252 (scroll move things according to line vector). Will have to make a test wad to see if there is a difference between voodoo / avatars (online) when using this method of scroller.

**Comment by rakohus** [comment] 2024-02-12 02:59
[252test.zip](https://github.com/odamex/odamex/files/14234938/252test.zip)

Ok, I figured it out. The bug is rooted in how voodoo (offline) vs. avatars (online) work. Voodoos are considered "players", through and through. Avatars, however, fall subject to monster properties. In this case, "block monster" or "block land monster" will stop the avatar from moving further on the conveyor.

The test wad has 3 setups: 
1) The one closest to the player is the one found in BoSCP map05. 

2) The middle does away with the lost soul and is unobstructed (that must be activated by shooting, which is how the lift triggers in the original map because the sound wakes the lost soul up.) 

3) The furthest path is a straight path but has a block monster line in the center of it. The voodoo passes through and will enter the teleport loop. Online, however, the avatar will stop dead center. This is the root cause of the issue.

Avatars should not be subject to monster blocking lines. Resolving this should make the map function as intended online.

**Closed as completed** 2024-08-09 03:16 UTC
Labels: Type-Bug, Component-Client, Component-Server, Subsystem-ActorBehavior, Subsystem-MapFormat
